project:
  type: website
  output-dir: _site
  resources:
    - styles.scss
    - _partials/**
  render:
    - index.qmd
    - about.qmd
  post-render:
    - cp -r manuscript/_manuscript _site/manuscript

format:
  revealjs:
    self-contained: true
    theme: default
    css: styles.scss
    slide-number: true
    progress: true
    hash: true
    center: false
    navigation-mode: linear
    title-slide-attributes:
      data-background-color: "#13294B"
    include-in-header:
      - _partials/header.html
    include-after-body:
      - _partials/footer.html

execute:
  echo: false
  eval: false


